{{- $top := . -}}
{{- range $key, $landscape := .Values.landscapes }}
{{- if $landscape.grafana }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: {{ $landscape.name }}-grafana
  namespace: chetan
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination: 
    namespace: sidd
    server: https://kubernetes.default.svc
  project: default
  source:
  {{- if eq $landscape.name "hec98"}}
    path: charts
    repoURL: https://github.com/Sid129/Helm-test
    targetRevision: "1.3"
  {{- else}}
    path: blackbox
    repoURL: https://github.com/Sid129/Helm-test
    targetRevision: "1.3"
  {{- end }}
  syncPolicy: {}
{{- end}}
{{- end}}