on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04   
    steps:
     - name: Helm Chart Releaser
  # You may pin to the exact commit or the version.
  # uses: helm/chart-releaser-action@120944e66390c2534cc1b3c62d7285ba7ff02594
       uses: helm/chart-releaser-action@v1.2.0
       with:
    # The chart-releaser version to use (default: v1.2.0)
          version: # optional
    # The relative path to the chart-releaser config file
          config: # optional
    # The charts directory
          charts_dir: Test
    # The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)
          charts_repo_url: # optional
